services:
  # Backend API service
  - type: web
    name: podcast-recommender-api
    env: python
    region: oregon  # Choose the region closest to your users
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=4 --worker-class=gevent --bind=0.0.0.0:$PORT --timeout=30
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: ALLOWED_ORIGINS
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend static site
  - type: static
    name: podcast-recommender-frontend
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
